# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=4000)),
                ('Desc', models.TextField(max_length=4000)),
                ('slug', models.TextField(max_length=4000)),
                ('Timings', models.DateTimeField(auto_now_add=True)),
                ('language_accepted', models.TextField(max_length=4000)),
                ('url_code', models.TextField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=4000)),
                ('Prob_statement', models.TextField(max_length=8000)),
                ('sample_input', models.TextField(max_length=8000)),
                ('explanation', models.TextField(max_length=8000, null=True)),
                ('no_of_submission', models.IntegerField(default=0)),
                ('url_code', models.TextField(null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest', to='karmo.Contest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
