# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karmo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='slug',
        ),
    ]
