# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmo', '0002_remove_contest_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contest',
            name='Timings',
            field=models.DateTimeField(),
        ),
    ]
