# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-31 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmo', '0004_code_snippet_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_snippet',
            name='language',
            field=models.CharField(default='', max_length=224),
        ),
    ]
