# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-01 09:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('karmo', '0005_auto_20180531_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 9, 14, 42, 938859, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
