# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('karmo', '0007_auto_20180608_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.BooleanField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_contest', to='karmo.Contest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_ques', to='karmo.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='testcase',
            name='inpt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='outp',
            field=models.TextField(),
        ),
    ]
